revamping docker script

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -14,9 +14,8 @@ on:
 
 jobs:
 
-  go-training-ci:
-    name: 'Go Training Pipeline'
-
+  project-build:
+    name: 'Build project'
     runs-on: ubuntu-20.04
 
     steps:
@@ -52,7 +51,47 @@ jobs:
         run: |
           cd src/${{ env.TEAM_MEMBER_NAME }}
           docker build . -t ${{ env.IMAGE_TAG }}
+          mkdir -p ./images
+          docker save -o ./images/${{ env.TEAM_MEMBER_NAME }}.tar ${{ env.IMAGE_TAG }}
         id: d_build
+
+      - name: 'Cache Image'
+        uses: actions/upload-artifact@v2
+        with:
+          name: ${{ env.TEAM_MEMBER_NAME }}
+          path: ./images/${{ env.TEAM_MEMBER_NAME }}.tar
+        id: d_image_cache
+
+
+  service-deploy:
+    name: 'Deploy service'
+    runs-on: ubuntu-20.04
+    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Runs only when pushing to main
+
+    steps:
+
+      - name: 'Environment setup'
+        run: |
+          user=
+          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
+            user=${GITHUB_HEAD_REF##*/}
+          elif [[ $GITHUB_EVENT_NAME == 'push' ]]; then
+            commit_msg=$(echo "${{ github.event.head_commit.message }}" | head -n 1)
+            user=$(echo $commit_msg | grep -o 'team/.*' | cut -f2- -d/)
+          else
+            echo "Cannot figure out username"
+            exit 1
+          fi
+
+          if [[ -z "$user" ]]; then
+            echo "Got empty username"
+            exit 2
+          fi
+
+          echo "Running for user: $user"
+          echo "TEAM_MEMBER_NAME=$user" >> "$GITHUB_ENV"
+          echo "IMAGE_TAG=${{ secrets.REGISTRY_LOGIN_SERVER }}/$user:latest" >> "$GITHUB_ENV"
+        id: env_setup
 
       - name: 'AZ Login'
         uses: azure/docker-login@v1
@@ -61,12 +100,20 @@ jobs:
           username: ${{ secrets.REGISTRY_USERNAME }}
           password: ${{ secrets.REGISTRY_PASSWORD }}
         id: d_az_login
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+
+      # First need to fetch the image
+
+      - name: 'Retrieve Image'
+        uses: actions/download-artifact@v2
+        with:
+          name: ${{ env.TEAM_MEMBER_NAME }}
+          path: ./images
 
       - name: 'Docker Push'
-        run: docker push ${{ env.IMAGE_TAG }}
+        run: |
+          docker load -i -q ./images/${{ env.TEAM_MEMBER_NAME }}.tar
+          docker push ${{ env.IMAGE_TAG }}
         id: d_push
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
 
       - name: 'Kube Deploy'
         uses: actions-hub/kubectl@master
@@ -75,6 +122,5 @@ jobs:
         with:
           args: rollout restart deployment
         id: kube_deploy
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
 
 
